### ISSUE TITLE
Analyse HWF templates integration

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/Bulk-Load#129]
Templates can be found at https://github.com/EyeSeeTea/NHWA-Excel-Importer/tree/master/templates

Changes to the excel files:
- [x] Add versioning to cell A1
- [ ] ~Yes/No/Partial should change not only to true but also to false on hidden columns~ #153

Tasks:
- [x] Organize code to add custom templates
- [x] Create design mockups and validate them
- [x] Minor infrastructure changes for the first template
- [ ] ~Inclusion of 8 NHWA templates~ #151
- [ ] ~Make NHWA custom templates to only appear for NHWA datasets~ #152
